
    create table usuario (
        id bigint generated by default as identity (start with 1),
        hash blob(255),
        salt blob(255),
        nombreUsuario varchar(255),
        primary key (id)
    )

    create table validaciones (
        tipo varchar(31) not null,
        id bigint generated by default as identity (start with 1),
        primary key (id)
    )
